"""Framework train, evaluate, infer, export, and gradient-verification APIs."""

from ..distributed import (
    DABSNSequenceModule,
    DistributedState,
    autocast_context,
    cleanup_distributed,
    clip_grad_norm,
    load_distributed_optimizer,
    load_sharded_model_checkpoint,
    load_sharded_training_checkpoint,
    make_grad_scaler,
    no_sync_context,
    parse_parallel_topology,
    prepare_distributed_model,
    prepare_distributed_module,
    resolve_precision,
    save_distributed_dabsn,
    save_sharded_training_checkpoint,
    setup_distributed,
    shard_batch,
    unwrap_dabsn_artifact,
    unwrap_dabsn_model,
    wrap_distributed,
)
from .api import (
    apply_optimizer_step,
    evaluate,
    export_dabsn,
    infer,
    train,
    train_step,
    verify_gradients,
)
from .dispatch import log_routing_once, reset_routing_log, warn_routing_once
from .grad_accum import ManualGradientAccumulator
from .graph import make_graphed_train_callable
from .loss import (
    ChunkedLinearCrossEntropy,
    chunked_cross_entropy_from_logits,
    chunked_linear_cross_entropy,
)

__all__ = [
    "DABSNSequenceModule",
    "DistributedState",
    "autocast_context",
    "apply_optimizer_step",
    "cleanup_distributed",
    "ChunkedLinearCrossEntropy",
    "chunked_cross_entropy_from_logits",
    "chunked_linear_cross_entropy",
    "log_routing_once",
    "reset_routing_log",
    "warn_routing_once",
    "clip_grad_norm",
    "evaluate",
    "export_dabsn",
    "infer",
    "load_distributed_optimizer",
    "load_sharded_model_checkpoint",
    "load_sharded_training_checkpoint",
    "make_grad_scaler",
    "make_graphed_train_callable",
    "ManualGradientAccumulator",
    "no_sync_context",
    "parse_parallel_topology",
    "prepare_distributed_model",
    "prepare_distributed_module",
    "resolve_precision",
    "save_distributed_dabsn",
    "save_sharded_training_checkpoint",
    "setup_distributed",
    "shard_batch",
    "train",
    "train_step",
    "unwrap_dabsn_model",
    "unwrap_dabsn_artifact",
    "verify_gradients",
    "wrap_distributed",
]
